language: node_js
node_js:
  - '0.12'
  - '0.10'
addons:
  code_climate:
    repo_token:
      secure: GAqKb08fKO3/TJwgd0xCz14O+jZPffZ5+ofctFOEBu2RQ52yBmVPIHH63b0/pKg4jR1AOu6uTt34Tpi0z8pme02RcACU47ZfP1wd2xsWAntx4iZFROaZnI/yvOZYHerG4QF3SBXd29rw7WLJ16sFhsCtyq1Sx+/b8zzf7V/0NjPGAc0gkc/xqShj5pdtJmpVbd9UPGRzjoid01zL2MII+OS8SfGRAGA0/my0WMDVcM8qkmNWseQgtVksSk7VWrJmjXOo6LZY14Bdcg13FVdT0+hsZOvsQgS6uf1Bs52PsfF5RbgVnWdWX36HJ7ImGWJvVfUXPM2oyNfEbylD/ThNxH3hz5GOk8xL84PASsHa0hQb/WrBuz+A4khaviH/kHg3oUF4eFTJhZilfTg6GGXWqqPZlCB69DCXtTO6VKnx/J1ac7X8GPfvo/3yY6v7Fin9aNG4hbJAhuUsWG+ax09pV7G1sEERIwpiDGjdS6UiHwcVqONJQlR4h9jTlEY+Fh+osY3CpIXrzQOYI4ffFs3IkBDxxxtUqtF3eZ/mCFGKLaE3fcQKDUFCNd4itw8zQs1oLku66v4LiymIJ3f7wE9OJB9N+SrFAfWtD8EIsDL8zvKTUCYILWkDrFTVBwcoI5piHZ4qaHttVS2m8CvvVNOhOVYhg/ou6sg+NMnwR0PekEw=
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - bower install
  - grunt
  - grunt karmaconfig
script: grunt test
env:
  matrix:
    - DEPLOY_BRANCH=hypermap
  global:
    secure: HppnhZMk+tZvDsuPelDnjfnKTH4hhHepElR8fNpOscEy5cpWQKb4BWmayw6rsfIvF5E36P5uL7sGyDsc0QVf0XvarX3CrHBZ0oZC/1rS5P9EXVJAPSsKpsNuN55JDtPL1eq7AC5NvP1kfWPQNVqWjmbQt5c6FBgm3dfvLUCD7YYthIEUoFwErmnLrWRXzdB4rFNF3BZa8sJ8/u6/meNPoqKjcWVLcbHLBOmc1pG51bSD+PYFjhYZLOqQfuI6Ix23isClhIGcWeENt/4jPHjQlVX6aivwmvIZ4ioK6iQQopEbq/VV9ACkgY1Q80zCcRwsTFPS6fAjAy4PVcFytSfF3wBoBjJmUM4qv9YJn9axx8rGeIVkORyU3RNT/sbZpeQfiB6hd1WpWeI4G8iXNHwgUjjF0FteXMHqrQOzy8UhG+eLIIpOhZe7mvNxlx0PvSQaIPoVtgU6dlJrAmZ3mLPtqomF9if/my1/zN5XaiJo2JGvwcNKHN8A25XBM1S1xaovra8L5eH3SSAOPTN/MvxJWlJqlOyRxbi9lCJdGw6Dacem3iqvCED/1QZYPbfSINV/f7WM4JUDOSAttHvt1mf4m8uhGM0sWXTZok/AIOx7Xe8Qh55TYyLr+Nx9F/vNDEQbN+vWpbrRg+SPosW8B1hWI1Q2rJRfLwS5GU2EwfY0BV8=
after_success:
  - grunt deploy
after_script:
  - codeclimate-test-reporter < reports/coverage/lcov.info
