version: '2'
services:

  maploom:
    build: .
    volumes:
      - './src:/usr/src/app/src'
    ports:
      - "3000:3000"

  postgres:
    image: postgres

  elasticsearch:
   image: elasticsearch
   ports:
      - "9200:9200"

  rabbitmq:
     image: rabbitmq

  django:
    image: terranodo/registry
    links:
      - postgres
      - elasticsearch
      - rabbitmq
    environment:
      - REGISTRY_SEARCH_URL=elasticsearch+http://elasticsearch:9200/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - ALLOWED_HOSTS=['django',]
  celery:
    image: terranodo/registry
    links:
      - rabbitmq
      - postgres
      - elasticsearch
    command: celery worker --app=hypermap.celeryapp:app -B -l INFO
    environment:
      - REGISTRY_SEARCH_URL=elasticsearch+http://elasticsearch:9200/
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/postgres
      - BROKER_URL=amqp://guest:guest@rabbitmq:5672/
      - ALLOWED_HOSTS=['django',]
      - C_FORCE_ROOT=1

  nginx:
    image: terranodo/nginx:3k8k
    links:
      - django
      - maploom
    ports:
      - "80:80"
